from crewai import Task
from agents import get_strategist, get_partner

def get_drafting_task():
    return Task(
        description=(
            "CRITICAL: You have been provided with a LIVE SCREENER \n"
            "DATA SNAPSHOT. You MUST use ONLY these exact figures in \n"
            "your analysis. Do not use any financial data from your \n"
            "training knowledge. The live snapshot is the ONLY source \n"
            "of truth for all financial figures.\n\n"
            "When writing the Situation section, copy the exact \n"
            "numbers from the snapshot:\n"
            "- Market Cap: use exact value from snapshot\n"
            "- Current Price: use exact value from snapshot  \n"
            "- ROCE: use exact value from snapshot\n"
            "- ROE: use exact value from snapshot\n"
            "- Stock P/E: use exact value from snapshot\n\n"
            "If a number is not in the snapshot, say 'data \n"
            "unavailable'. Never use numbers from memory.\n\n"
            "You are the Principal Strategist. Analyze the following data for the company '{company_name}' "
            "regarding the specific business problem: '{problem}'.\n\n"
            "DATA:\n{research_data}\n\n"
            "INSTRUCTIONS:\n"
            "1. Select the most appropriate strategic framework (e.g., Porter's Five Forces, BCG Matrix, McKinsey 7S, PESTLE) for this specific problem based on your prompt rules.\n"
            "2. State why you selected this framework citing author and year.\n"
            "3. Draft 3 mutually exclusive, highly specific strategic options to solve the problem.\n"
            "4. For each option, write out the Pros, Cons, and a high-level roadmap.\n"
            "This is a DRAFT, but make it as brilliant as possible.\n\n"
            "Your 3 options must be specific to THIS company and THIS \n"
            "problem. Do not use generic archetype names like \n"
            "'Operational Excellence', 'Product Leadership', or \n"
            "'Customer Intimacy' as option titles.\n\n"
            "Before writing options, re-read \n"
            "the problem statement carefully. Every option MUST \n"
            "directly address the specific problem stated. If the \n"
            "problem is about gig worker strikes, all 3 options must \n"
            "be responses to the gig worker strike — not fuel costs, \n"
            "not unrelated issues. Test each option against the \n"
            "problem: does this option directly solve or address \n"
            "the specific problem stated? If not, rewrite it.\n\n"
            "Instead, use specific action-oriented names that reference:\n"
            "- The company's actual business units or product lines\n"
            "- The specific problem being analyzed\n"
            "- Concrete strategic actions\n\n"
            "Examples of BAD option names (too generic):\n"
            "- Option 1: Operational Excellence\n"
            "- Option 2: Product Leadership  \n"
            "- Option 3: Customer Intimacy\n\n"
            "Examples of GOOD option names (specific and action-oriented):\n"
            "- For Zomato gig worker problem:\n"
            "  Option 1: Convert Top 20% Riders to Fixed-Cost Employment\n"
            "  Option 2: Deploy AI Route Optimization to Reduce Rider \n"
            "             Workload Per Order\n"
            "  Option 3: Build Captive Rider Fleet via Franchise Model\n\n"
            "- For Titan gold advisory problem:\n"
            "  Option 1: Accelerate Tanishq Digital Gold Advisory Platform\n"
            "  Option 2: Hedge Revenue via Gold Price Forward Contracts\n"
            "  Option 3: Expand CaratLane into Tier 2 Advisory Network\n\n"
            "- For Infosys visa problem:\n"
            "  Option 1: Accelerate Local Hiring in US to Reduce Visa \n"
            "             Dependency\n"
            "  Option 2: Shift Delivery Model to Offshore-First for \n"
            "             Affected Contracts\n"
            "  Option 3: Acquire US-Based Boutique Firm for Local Talent\n\n"
            "When Treacy & Wiersema Value Disciplines is the \n"
            "selected framework, the 3 options must NOT be named \n"
            "'Operational Excellence', 'Customer Intimacy', or \n"
            "'Product Leadership' directly.\n\n"
            "Instead name them as specific strategic actions:\n"
            "- Instead of 'Operational Excellence' → \n"
            "  'Consolidate Payment Infrastructure to Reduce \n"
            "  Transaction Costs by X%'\n"
            "- Instead of 'Customer Intimacy' → \n"
            "  'Build Paytm SuperApp Loyalty Ecosystem for \n"
            "  High-Value Users'\n"
            "- Instead of 'Product Leadership' → \n"
            "  'Launch Paytm Financial Services Suite targeting \n"
            "  Tier 2 credit gap'\n\n"
            "The discipline name can appear in the Overview text \n"
            "as context but never as the option title itself.\n\n"
            "The rule: If the option name could apply to ANY company \n"
            "facing ANY problem, it is too generic. Rewrite it until \n"
            "it could ONLY apply to this specific company and this \n"
            "specific problem.\n\n"
            "CRITICAL CONSTRAINT: NEVER invent financial figures. Only use numbers that appear in the provided Screener.in data or news articles. "
            "If a number is unavailable, say 'data unavailable' — never estimate or guess. All figures must be in INR not USD since these are Indian companies."
        ),
        expected_output="A structured first draft of the strategy, specifying the framework used and 3 distinct options.",
        agent=get_strategist()
    )

def get_critique_task():
    return Task(
        description=(
            "CRITICAL: You have been provided with a LIVE SCREENER \n"
            "DATA SNAPSHOT. You MUST use ONLY these exact figures in \n"
            "your analysis. Do not use any financial data from your \n"
            "training knowledge. The live snapshot is the ONLY source \n"
            "of truth for all financial figures.\n\n"
            "When writing the Situation section, copy the exact \n"
            "numbers from the snapshot:\n"
            "- Market Cap: use exact value from snapshot\n"
            "- Current Price: use exact value from snapshot  \n"
            "- ROCE: use exact value from snapshot\n"
            "- ROE: use exact value from snapshot\n"
            "- Stock P/E: use exact value from snapshot\n\n"
            "If a number is not in the snapshot, say 'data \n"
            "unavailable'. Never use numbers from memory.\n\n"
            "You are the Senior Partner & Devil's Advocate. Review the following draft strategy proposed by your Principal Strategist "
            "for the company '{company_name}' regarding the problem '{problem}'.\n\n"
            "DRAFT STRATEGY:\n{draft_strategy}\n\n"
            "INSTRUCTIONS:\n"
            "Tear this draft apart. Do not hold back.\n"
            "1. Find at least 2 major logical flaws, blind spots, or risks they completely missed in the proposed options.\n"
            "2. Identify if the chosen framework was actually the right choice, or if they applied it poorly.\n"
            "3. Provide exactly 3 Brutal Directives for how the Principal MUST improve the strategy in the final version.\n"
            "Be aggressive, extremely analytical, and demanding."
        ),
        expected_output="A brutal, high-level critique with 3 strict directives for improvement.",
        agent=get_partner()
    )

def get_final_polish_task():
    return Task(
        description=(
            "CRITICAL: You have been provided with a LIVE SCREENER \n"
            "DATA SNAPSHOT. You MUST use ONLY these exact figures in \n"
            "your analysis. Do not use any financial data from your \n"
            "training knowledge. The live snapshot is the ONLY source \n"
            "of truth for all financial figures.\n\n"
            "When writing the Situation section, copy the exact \n"
            "numbers from the snapshot:\n"
            "- Market Cap: use exact value from snapshot\n"
            "- Current Price: use exact value from snapshot  \n"
            "- ROCE: use exact value from snapshot\n"
            "- ROE: use exact value from snapshot\n"
            "- Stock P/E: use exact value from snapshot\n\n"
            "If a number is not in the snapshot, say 'data \n"
            "unavailable'. Never use numbers from memory.\n\n"
            "You are the Principal Strategist. You have received a brutal critique from your Senior Partner "
            "regarding your draft strategy for '{company_name}'.\n\n"
            "YOUR ORIGINAL DRAFT:\n{draft_strategy}\n\n"
            "THE PARTNER'S CRITIQUE:\n{partner_critique}\n\n"
            "INSTRUCTIONS:\n"
            "You must rewrite the strategy into a final, flawless Consulting Brief. "
            "Incorporate ALL of the Partner's feedback and fix the logical flaws they identified.\n\n"
            "When Treacy & Wiersema Value Disciplines is the \n"
            "selected framework, the 3 options must NOT be named \n"
            "'Operational Excellence', 'Customer Intimacy', or \n"
            "'Product Leadership' directly.\n\n"
            "Instead name them as specific strategic actions:\n"
            "- Instead of 'Operational Excellence' → \n"
            "  'Consolidate Payment Infrastructure to Reduce \n"
            "  Transaction Costs by X%'\n"
            "- Instead of 'Customer Intimacy' → \n"
            "  'Build Paytm SuperApp Loyalty Ecosystem for \n"
            "  High-Value Users'\n"
            "- Instead of 'Product Leadership' → \n"
            "  'Launch Paytm Financial Services Suite targeting \n"
            "  Tier 2 credit gap'\n\n"
            "The discipline name can appear in the Overview text \n"
            "as context but never as the option title itself.\n\n"
            "The rule: If the option name could apply to ANY company \n"
            "facing ANY problem, it is too generic. Rewrite it until \n"
            "it could ONLY apply to this specific company and this \n"
            "specific problem.\n\n"
            "CRITICAL CONSTRAINT: NEVER invent financial figures. Only use numbers that appear in the provided Screener.in data or news articles. "
            "If a number is unavailable, say 'data unavailable' — never estimate or guess. All figures must be in INR not USD.\n\n"
            "Your output MUST be formatted EXACTLY like this for the downstream PDF generator:\n"
            "# StratAgent Brief: {company_name}\n"
            "## Problem: {problem}\n"
            "## Framework Selected: [Name of Framework + author and year + one line why THIS framework fits THIS problem — not a generic description]\n"
            "## Situation\n"
            "[2-3 sentences using ACTUAL numbers from Screener.in data]\n"
            "[Example: 'Titan reported ROCE of X% and PE of Y, indicating...']\n"
            "## Strategic Tension\n"
            "[Single most important tension — specific to this company]\n"
            "## Option 1: [Name]\n"
            "Overview: [specific to THIS company, use real numbers]\n"
            "Pros: [3 bullet points]\n"
            "Cons: [3 bullet points]\n"
            "Roadmap: [3-5 specific action steps]\n"
            "## Option 2: [Name]\n"
            "[Follow the same structure as Option 1]\n"
            "## Option 3: [Name]\n"
            "[Follow the same structure as Option 1]\n"
            "## Recommendation\n"
            "[Single clear recommendation with rationale using data]\n"
            "## Data Confidence\n"
            "Score: {confidence_score}/5\n"
            "Sources: [list sources provided]\n"
            "Data Gaps: [what was missing]\n"
            "Key Assumptions: [list]\n\n"
            "## METRICS FOR CHART\n"
            "ROCE: [Extracted value from data, or 'Data unavailable']\n"
            "ROE: [Extracted value from data, or 'Data unavailable']\n"
            "PE: [Extracted value from data, or 'Data unavailable']\n"
            "\n"
            "IMPORTANT: At the end of your response, you MUST include \n"
            "this exact block using the numbers from the Screener.in \n"
            "data provided to you. Do not say Data unavailable if the \n"
            "number exists in the Screener snapshot.\n"
            "The METRICS FOR CHART block MUST use the ROCE, \n"
            "ROE, and Stock P/E values from the Screener.in snapshot \n"
            "provided in THIS analysis. Do not reuse numbers from \n"
            "any previous analysis or examples.\n\n"
            "## METRICS FOR CHART\n"
            "ROCE: [exact value from Screener snapshot]\n"
            "ROE: [exact value from Screener snapshot]\n"
            "PE: [exact value from Stock P/E from Screener snapshot]\n\n"
            "These values MUST be plain numbers only — no %, no Rs., \n"
            "no Cr. Just the number."
        ),
        expected_output="The final, flawless Consulting Brief, perfectly formatted.",
        agent=get_strategist()
    )
